/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffc5a4",
        "primary": "#0846ed",
        "on-surface-variant": "#585781",
        "tertiary-fixed": "#00cffc",
        "secondary-fixed-dim": "#ffb284",
        "primary-dim": "#003cd3",
        "surface-container": "#e9e5ff",
        "outline": "#74739e",
        "on-surface": "#2b2a51",
        "on-primary-fixed-variant": "#00207e",
        "on-secondary-fixed-variant": "#843c00",
        "primary-fixed": "#859aff",
        "on-tertiary-container": "#004050",
        "primary-fixed-dim": "#718bff",
        "error": "#b41340",
        "secondary-dim": "#823b00",
        "error-container": "#f74b6d",
        "surface": "#f9f5ff",
        "inverse-primary": "#6d88ff",
        "secondary-container": "#ffc5a4",
        "on-error-container": "#510017",
        "tertiary-dim": "#00576c",
        "on-secondary-container": "#763500",
        "tertiary": "#00647b",
        "tertiary-fixed-dim": "#00c0ea",
        "surface-variant": "#dcd9ff",
        "inverse-surface": "#0a082f",
        "secondary": "#954400",
        "on-primary": "#f2f1ff",
        "on-primary-container": "#001867",
        "inverse-on-surface": "#9a99c6",
        "tertiary-container": "#00cffc",
        "on-error": "#ffefef",
        "background": "#f9f5ff",
        "surface-dim": "#d2d0ff",
        "outline-variant": "#aba9d7",
        "on-secondary-fixed": "#582600",
        "primary-container": "#859aff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#e2f6ff",
        "surface-tint": "#0846ed",
        "surface-container-high": "#e2dfff",
        "on-secondary": "#fff0e9",
        "surface-container-low": "#f2efff",
        "on-tertiary-fixed-variant": "#004a5c",
        "surface-container-highest": "#dcd9ff",
        "error-dim": "#a70138",
        "on-background": "#2b2a51",
        "surface-bright": "#f9f5ff",
        "on-tertiary-fixed": "#002a35",
        "on-primary-fixed": "#000000"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      }
    }
  },
  plugins: [],
};
